[env:esp8684-mini-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312-1/platform-espressif32.zip
board = esp32-c2-devkitm-1
framework = espidf
monitor_speed = 115200
monitor_port = COM131
upload_port = COM131
upload_speed = 115200
board_build.flash_mode = dio
board_upload.flash_size = 4MB
