[env:esp8684-mini-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312-1/platform-espressif32.zip
board = esp32-c2-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_port = COM131
upload_port = COM131
upload_speed = 115200
board_build.flash_mode = dio
board_upload.flash_size = 4MB
custom_sdkconfig =
    CONFIG_XTAL_FREQ_26=y
    CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_120=y
    CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ=120
    CONFIG_ESPTOOLPY_FLASHMODE_DIO=y
    CONFIG_ESPTOOLPY_FLASHFREQ_60M=y
    CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y
