; ESP8684-MINI-1 (ESP32-C2) — SoftAP web server
; Tools on Windows: D:\DEV_ESP32
; Projects on Windows: D:\MCS_ESP32
; Upload port: COM131

[env:esp8684-mini-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c2-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
upload_port = COM131
monitor_port = COM131
board_build.flash_mode = dio
board_build.f_flash = 60000000L
build_flags =
	-DCORE_DEBUG_LEVEL=1
